version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        GQL_HOST: "/graphql"
    ports:
      - 8000:3000
    environment:
      PORT: 8000
      GQL_HOST: "/graphql"
      NUXT_PUBLIC_REST_HOST: "/api"

    networks:
      - app-network
    depends_on:
      - backend

  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      ACCESS_TOKEN_SECRET: "access_secret"
      ACCESS_TOKEN_EXPIRATION: "1h"
      REFRESH_TOKEN_SECRET: "refresh_secret"
      MONGODB_URI: "mongodb://wetravel:wetravel@mongodb:27017/wetravel?authSource=admin"

    networks:
      - app-network
    depends_on:
      - mongodb
      
  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
  
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: wetravel
      MONGO_INITDB_ROOT_PASSWORD: wetravel
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge