mutation CreateTravel($input: CreateTravelInput!) {
  createTravel(createTravelInput: $input) {
    id
    title
    duration
    description
    public
    slug
    images {
      url
      originalname
      filename
    }
  }
}

mutation RemoveTravel($id: ID!) {
  removeTravel(id: $id) {
    id
  }
}
