query getTravels($limit: Int) {
  travels(limit: $limit) {
    title
    description
    images {
      url
      originalname
      filename
    }
    slug
  }
}

query getTravelBySlug($slug: String!) {
  travelBySlug(slug: $slug) {
    id
    title
    description
    images {
      url
      originalname
      filename
    }
    slug
    duration
    public
  }
}
