query getTravels($limit: Int, $skip: Int) {
  travels(limit: $limit, skip: $skip) {
    items {
      id
      title
      description
      images {
        url
        originalname
        filename
      }
      slug
    }
    count
  }
}

query getTravelBySlug($slug: String!) {
  travelBySlug(slug: $slug) {
    id
    title
    description
    images {
      url
      originalname
      filename
    }
    slug
    duration
    public
  }
}
